
services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: psql
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: postgres
    ports:
      - "5431:5432"
    networks:
      - mynetwork

  api:
    build: 
      context: .
    container_name: fastapi-app
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - mynetwork

networks:
  mynetwork: